# PIPELINE DEFINITION
# Name: training
# Inputs:
#    batch_size: int
#    early_stopping_patience: int
#    early_stopping_threshold: float
#    epochs: int
#    eval_steps: int
#    gradient_accumulation_steps: int
#    label_mapping: str
#    learning_rate: float
#    model_dir: str
#    pretrained_model: str
#    train_set: str
#    val_set: str
components:
  comp-training:
    executorLabel: exec-training
    inputDefinitions:
      parameters:
        batch_size:
          description: Batch size for training.
          parameterType: NUMBER_INTEGER
        early_stopping_patience:
          description: Number of epochs to wait before early stopping.
          parameterType: NUMBER_INTEGER
        early_stopping_threshold:
          description: Threshold for early stopping.
          parameterType: NUMBER_DOUBLE
        epochs:
          description: Number of epochs for training.
          parameterType: NUMBER_INTEGER
        eval_steps:
          description: Number of steps to run evaluation.
          parameterType: NUMBER_INTEGER
        gradient_accumulation_steps:
          description: Number of steps to accumulate gradients.
          parameterType: NUMBER_INTEGER
        label_mapping:
          description: Label mapping path on GCS in JSON format.
          parameterType: STRING
        learning_rate:
          description: Learning rate for training.
          parameterType: NUMBER_DOUBLE
        model_dir:
          description: Model directory path on GCS.
          parameterType: STRING
        pretrained_model:
          description: Pretrained model name on Huggingface model hub.
          parameterType: STRING
        train_set:
          description: Train dataset path on GCS in CSV format.
          parameterType: STRING
        val_set:
          description: Validation dataset path on GCS in CSV format.
          parameterType: STRING
deploymentSpec:
  executors:
    exec-training:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - training
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'protobuf==3.20.1'\
          \ 'fsspec==2022.11.0' 'gcsfs==2022.11.0' 'google-cloud-secret-manager' 'google-cloud-bigquery'\
          \ 'google-cloud-bigquery-storage' 'scikit-learn' 'pandas==1.5.2' 'evaluate'\
          \ && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.components.executor_main
        image: us-central1-docker.pkg.dev/independent-bay-388105/public/training
pipelineInfo:
  name: training
root:
  dag:
    tasks:
      training:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-training
        inputs:
          parameters:
            batch_size:
              componentInputParameter: batch_size
            early_stopping_patience:
              componentInputParameter: early_stopping_patience
            early_stopping_threshold:
              componentInputParameter: early_stopping_threshold
            epochs:
              componentInputParameter: epochs
            eval_steps:
              componentInputParameter: eval_steps
            gradient_accumulation_steps:
              componentInputParameter: gradient_accumulation_steps
            label_mapping:
              componentInputParameter: label_mapping
            learning_rate:
              componentInputParameter: learning_rate
            model_dir:
              componentInputParameter: model_dir
            pretrained_model:
              componentInputParameter: pretrained_model
            train_set:
              componentInputParameter: train_set
            val_set:
              componentInputParameter: val_set
        taskInfo:
          name: training
  inputDefinitions:
    parameters:
      batch_size:
        description: Batch size for training.
        parameterType: NUMBER_INTEGER
      early_stopping_patience:
        description: Number of epochs to wait before early stopping.
        parameterType: NUMBER_INTEGER
      early_stopping_threshold:
        description: Threshold for early stopping.
        parameterType: NUMBER_DOUBLE
      epochs:
        description: Number of epochs for training.
        parameterType: NUMBER_INTEGER
      eval_steps:
        description: Number of steps to run evaluation.
        parameterType: NUMBER_INTEGER
      gradient_accumulation_steps:
        description: Number of steps to accumulate gradients.
        parameterType: NUMBER_INTEGER
      label_mapping:
        description: Label mapping path on GCS in JSON format.
        parameterType: STRING
      learning_rate:
        description: Learning rate for training.
        parameterType: NUMBER_DOUBLE
      model_dir:
        description: Model directory path on GCS.
        parameterType: STRING
      pretrained_model:
        description: Pretrained model name on Huggingface model hub.
        parameterType: STRING
      train_set:
        description: Train dataset path on GCS in CSV format.
        parameterType: STRING
      val_set:
        description: Validation dataset path on GCS in CSV format.
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.0.1
